name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    tags:
      - 'v*'  # Trigger on tags starting with 'v' (e.g., v1.0.0)
  pull_request:
    branches:
      - main  # Optional: Trigger on pull requests to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.OWNER_LC }}/${{ github.event.repository.name }}:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.OWNER_LC }}/${{ github.event.repository.name }}:latest

      - name: Tag and Push versioned image (if tagged)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/${{ github.OWNER_LC }}/${{ github.event.repository.name }}:latest ghcr.io/${{ github.OWNER_LC }}/${{ github.event.repository.name }}:$TAG
          docker push ghcr.io/${{ github.OWNER_LC }}/${{ github.event.repository.name }}:$TAG